development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: repertoire_faceting_example
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: repertoire_faceting_example
  pool: 5
  username: postgres
  password:
